## Pytorch framework

In [2]:
pip install torch

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 899.7/899.7 MB 5.5 MB/s eta 0:00:00:00:0100:02
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 594.3/594.3 MB 8.8 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 23.1 MB/s eta 0:00:0000:010:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.0/88.0 MB 15.8 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 954.8/954.8 kB 18.4 MB/s eta 0:00:0000:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 706.8/706.8 MB 6.7 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.1/193.1 MB 9.2 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 9.9 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.6/63.6 MB 10.6 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 267.5/267.5 MB 12.2 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 288.2/288.2 MB 10.9 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━

In [2]:
import torch

In [3]:
if torch.cuda.is_available() :
    print("Gpu!!!")
    print(torch.cuda.get_device_name())
else:
    print("No gpu was harmed during this")

Gpu!!!
NVIDIA GeForce RTX 4050 Laptop GPU


To make a tensor, just write torch.tensor :

In [13]:
torch.tensor(5)

tensor(5)

In [14]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
torch.rand(2,4)

tensor([[0.9478, 0.8520, 0.8369, 0.7293],
        [0.5247, 0.8860, 0.3985, 0.0301]])

for generating the same random numbers, set a manual seed

In [21]:
torch.manual_seed(42)
x=torch.rand(2,4)
x

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936]])

In [22]:
torch.manual_seed(42)
y=torch.rand(2,4)
y

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936]])

In [24]:
print(torch.sigmoid(x))
print(torch.softmax(x, dim=0))

tensor([[0.7073, 0.7140, 0.5946, 0.7230],
        [0.5964, 0.6459, 0.5638, 0.6886]])
tensor([[0.6205, 0.5779, 0.5315, 0.5413],
        [0.3795, 0.4221, 0.4685, 0.4587]])


In [29]:
device = torch.device('cuda')
a = torch.rand((2,3), device=device)        #GPU accelerated tensor
a

tensor([[0.9877, 0.1289, 0.5621],
        [0.5221, 0.7445, 0.5955]], device='cuda:0')

In [53]:
import time
size = 2000
mat1 = torch.rand(size,size)
mat2 = torch.rand(size,size)
mat3 = mat1.to("cuda")
mat4 = mat2.to("cuda")    # or  torch.rand(size,size,device=device)

In [54]:
#time taken by cpu tensors
start_tim = time.time()
mul_cpu = torch.matmul(mat1,mat2)
cpu_tim = time.time()-start_tim
print(f"Cpu_time={cpu_tim:.4f}")

Cpu_time=0.0444


In [55]:
#time by gpu tensors
start_time = time.time()
mul_cpu = torch.matmul(mat3,mat4)
gpu_tim = time.time()-start_time
print(f"Gpu_time={gpu_tim:.4f}")

Gpu_time=0.0014


### Logistic regression

In [28]:
x = torch.tensor(2.3)
y_true = torch.tensor(0.0)

w=torch.tensor(3.14, requires_grad = True)
b=torch.tensor(0.00, requires_grad = True)
z= w*x + b
z

tensor(7.2220, grad_fn=<AddBackward0>)

In [29]:
def binary_cross_entropy(prediction, target):
    eps = 1e-8
    prediction = torch.clamp(prediction, eps, 1-eps)               # to prevent zero value                                 
    loss = -(target*torch.log(prediction) + (1-target)*torch.log(1-prediction))
    return loss

In [30]:
y_pred = torch.sigmoid(z)
loss = binary_cross_entropy(y_pred, y_true)

In [31]:
loss.backward()      # Backprop

In [32]:
print(w.grad)
print(b.grad)

tensor(2.2983)
tensor(0.9993)


In [35]:
w.grad.zero_()
b.grad.zero_()    # Required to clear up the tensor, bcoz value will add up when multiple passes are run

tensor(0.)

In [37]:
# w.requires_grad()  or
#  with torch.no_grad() : \n z = wx+b 
# are some functions that r needed to stop the gradient process, in places like NN